### ISSUE TITLE
Team cards are not rendered correctly on the home page

### ISSUE THREAD

**Issue by PChaparro** [midudev/kings-league-project#277]
![image](https://user-images.githubusercontent.com/94259578/211222428-814dd679-d2de-4dc9-ae8a-08ed671e8fc4.png)

**Comment by felipetodev** [comment]
This error were fixed by closing this div #267 https://github.com/midudev/kings-league-project/pull/267/commits/76ead8243ed134e2312f66026cad234b7a9231f3

## Screenshot:
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/69825873/211222732-8d691b8e-8e36-4b29-b9b5-fe534790ccf3.png">

**Comment by PChaparro** [comment]
Fixed by Midu in commit [79371b1ce7394ecbb90af17962404d380a22f200](https://github.com/midudev/kings-league-project/commit/79371b1ce7394ecbb90af17962404d380a22f200).
